# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Minh Khanh's Blog
author: Khanh H.
email: minhkhanhhoang2105@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true

# Build settings
remote_theme: thelehhman/plainwhite-jekyll
theme: plainwhite
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Customize the theme data
sass:
  sass_dir: _sass
plainwhite:
  name: Khanh H.
  tagline: Software Developer
  date_format: "%b %-d, %Y"
  sitemap: true

  social_links:
    twitter: minhkhanh_h
    github: limmiehoang
    linkedIn: in/htmkhanh
    facebook: htmkhanh
    rss: rss
